Aplikacija/RIIEdition/Pages/UserPages/BazaBlanketa.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;

namespace RIIEdition.Pages.UserPages
{
    public class BazaBlanketaModel : PageModel
    {
        private readonly RIIDBContext db;
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;

        [BindProperty(SupportsGet = true)]
        public User MyUser { get; set; }

        [BindProperty(SupportsGet = true)]
        public IList<MaterijalData> MaterijalData { get; set; }

        public BazaBlanketaModel(RIIDBContext db, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.db = db;

            this.signInManager = signInManager;

            this.userManager = userManager;

        }
        public async Task OnGetAsync()
        {
            MyUser = await userManager.FindByNameAsync(User.Identity.Name);
            //Samo je potrebno da se ubaci za odredjenog usera
            MaterijalData = db.MaterijalData.ToList();
        }

    }
}

Aplikacija/RIIEdition/Pages/UserPages/BlanketNapravi.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;

namespace RIIEdition.Pages.UserPages
{


    [BindProperties]
    public class BlanketNapraviModel : PageModel
    {

        private readonly UserManager<User> userManager;
        private readonly RIIDBContext db;

        public BlanketNapraviModel(UserManager<User> userManager, RIIDBContext db)
        {
            this.db = db;
            this.userManager = userManager;

        }


        [Display(Name = "Opis materijala")]

        public string OpisMaterijala { get; set; }


        [Display(Name = "Pitanja materijala")]
        public string PitanjaMaterijala { get; set; }

        [Display(Name = "Odgovori materijala")]

        public string OdgovoriMaterijala { get; set; }

        [Display(Name = "Naziv materijala")]

        public string NazivMaterijala { get; set; }

        [Display(Name = "Ocena materijala")]


        public double OcenaMaterijala { get; set; }

        [Display(Name = "Predmet materijala")]



        public string PredmetMaterijala { get; set; }


        public User CurrentUser { get; set; }
        public void OnGet() { }
        public async Task<IActionResult> OnPost()
        {


            var user = await userManager.GetUserAsync(User);
            MaterijalData materijalData = new MaterijalData
            {
                NazivMaterijala = NazivMaterijala,

                PredmetMaterijala = PredmetMaterijala,
                PitanjaMaterijala = PitanjaMaterijala,
                brojOcenaJedan = 0,
                brojOcenaDva = 0,
                brojOcenaTri = 0,
                brojOcenaCetiri = 0,
                brojOcenaPet = 0,
                OdgovoriMaterijala = OdgovoriMaterijala,
                User = user
            };
            await db.MaterijalData.AddAsync(materijalData);
            await db.SaveChangesAsync();

            return RedirectToPage("/UserPages/MojiBlanketi");
        }
    }
}

Aplikacija/RIIEdition/Pages/UserPages/Calendar.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;

namespace RIIEdition.Pages.UserPages
{
    public class CalendarModel : PageModel
    {
        private readonly RIIDBContext db;
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;

        [BindProperty(SupportsGet = true)]
        public string[] Dogadjaji { get; set; }
        [BindProperty(SupportsGet = true)]
        public int[] Dani { get; set; }
        [BindProperty(SupportsGet = true)]
        public string[] Meseci { get; set; }
        [BindProperty(SupportsGet = true)]
        public bool[] CeliDani { get; set; }

        [BindProperty(SupportsGet = true)]
        public double[] Pocetak { get; set; }

        [BindProperty(SupportsGet = true)]
        public double[] Zavrsetak { get; set; }
        [BindProperty(SupportsGet = true)]
        public string[] OpisDogadjaja { get; set; }
        [BindProperty(SupportsGet = true)]
        public IList<CalendarData> CalendarDatas { get; set; }
        //Post propertiji
        [BindProperty]
        [Required(ErrorMessage = "Naziv dogadjaja je obavezan")]
        public string NoviDogadjaj { get; set; }
        [BindProperty]
        public string NoviOpisDogadjaja { get; set; }

        [Display(Name = "Celodnevni dogadjaj")]
        [BindProperty]
        public bool CeoDan { get; set; }
        [BindProperty]
        public string Mesec { get; set; }
        [BindProperty]
        public int Dan { get; set; }
        [BindProperty]
        [Display(Name = "Pocetak dogadjaja")]
        public string NoviPocetak { get; set; }
        [BindProperty]
        [Display(Name = "Kraj dogadjaja")]
        public string NoviZavrsetak { get; set; }



        public CalendarModel(RIIDBContext db, UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.db = db;
            this.userManager = userManager;
            this.signInManager = signInManager;
        }


        public async Task OnGetAsync()
        {
            var user = await userManager.GetUserAsync(User);
            if (user != null)
            {
                CalendarDatas = db.CalendarData.Where(x => x.User == user).ToList();

            }

        }
        public async Task<IActionResult> OnPostAsync()
        {
            var user = await userManager.GetUserAsync(User);
            if (!ModelState.IsValid)
            {

                return Page();
            }

            else
            {

                CalendarData date = new CalendarData
                {
                    Dan = Dan,
                    Mesec = Mesec,
                    User = user,
                    Pocetak = NoviPocetak,
                    Zavrestak = NoviZavrsetak,
                    opisDogadjaja = NoviOpisDogadjaja,
                    NazivDogadjaja = NoviDogadjaj,
                    CeoDan = CeoDan
                };
                await db.CalendarData.AddAsync(date);
                await db.SaveChangesAsync();

                return RedirectToPage("/UserPages/Calendar");
            }

        }
        public async Task<IActionResult> OnPostDeleteAsync(int Id)
        {
            var item = await db.CalendarData.FindAsync(Id);
            db.CalendarData.Remove(item);
            await db.SaveChangesAsync();
            return RedirectToPage();
        }

    }
}

Aplikacija/RIIEdition/Pages/UserPages/ChangePassword.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;

namespace RIIEdition.Pages.UserPages
{
    public class ChangePasswordModel : PageModel
    {
        private readonly UserManager<User> userManager;

        public ChangePasswordModel(UserManager<User> userManager)
        {
            this.userManager = userManager;
        }
        [BindProperty(SupportsGet = true)]
        public string Naziv { get; set; }
        public async Task<IActionResult> OnGetAsync(string userId, string token, string password)
        {

            var user = await userManager.FindByIdAsync(userId);
            var result = await userManager.ResetPasswordAsync(user, token, password);
            if (result.Succeeded)
                Naziv = "Uspesno ste promenili sifru";
            else
                Naziv = "Doslo je do greske pri menjaju sifre";
            return Page();
        }

    }
}

Aplikacija/RIIEdition/Pages/UserPages/ConfirmEmail.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;
using System.ComponentModel.DataAnnotations;

namespace RIIEdition.Pages.UserPages
{
    public class ConfirmEmailModel : PageModel
    {
        [BindProperty]
        [DataType(DataType.EmailAddress)]

        public string Email { get; set; }
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        public ConfirmEmailModel(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }


        [BindProperty(SupportsGet = true)]
        public string Error { get; set; } = "1";

        public async Task<IActionResult> OnGetAsync(string userId, string token)
        {
            if (userId == null || token == null)
                return Page();

            var user = await userManager.FindByIdAsync(userId);
            this.Email = user.Email;
            var result = await userManager.ConfirmEmailAsync(user, token);

            if (result.Succeeded)
            {
                return RedirectToPage("/UserPages/Login");
            }
            else
            {
                Error = "Desila se greska sa konfirmacijom mail.Molimo obratiti se adminisrtoru";
                return Page();
            }

        }
    }
}

Aplikacija/RIIEdition/Pages/UserPages/EditUserProfile.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RIIEdition.Pages.UserPages
{
    public class EditUserProfileModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Aplikacija/RIIEdition/Pages/UserPages/ExternalLoginCallback.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;

namespace RIIEdition.Pages.UserPages
{

    public class ExternalLoginCallbackModel : PageModel
    {
        private readonly SignInManager<User> signInManager;
        private readonly UserManager<User> userManager;

        public ExternalLoginCallbackModel(SignInManager<User> signInManager, UserManager<User> userManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }


        public async Task<IActionResult> OnGetAsync()
        {

            var info = await signInManager.GetExternalLoginInfoAsync();
            if (info == null)
            {

                ModelState.AddModelError("", "Error loading external logging information");
                return RedirectToPage("UserPages/Login");
            }
            var signInResult = await signInManager.ExternalLoginSignInAsync(info.LoginProvider, info.ProviderKey,
            isPersistent: false, bypassTwoFactor: true);

            if (signInResult.Succeeded)
            {

                return RedirectToPage("/Index");
            }
            else
            {

                var email = info.Principal.FindFirstValue(ClaimTypes.Email);
                if (email != null)
                {

                    var user = await userManager.FindByEmailAsync(email);

                    await signInManager.SignInAsync(user, isPersistent: false);

                    return RedirectToPage("/Index");
                }

            }

            ModelState.AddModelError("", "Ne postoji registrovani korisnik sa ovom adresom");
            return RedirectToPage("/UserPages/Login");



        }

    }
}

Aplikacija/RIIEdition/Pages/UserPages/FlashCards.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;

namespace RIIEdition.Pages.UserPages
{
    public class FlashCardsModel : PageModel
    {


        [BindProperty(SupportsGet = true)]
        public string Predmet { get; set; }

        [Display(Name = "brojPoenaDbFK")]
        [BindProperty(SupportsGet = true)]
        public string brojPoenaDbFK { get; set; }

        [Display(Name = "datumZavrsetkaDbFK")]
        [BindProperty(SupportsGet = true)]
        public string datumZavrsetkaDbFK { get; set; }

        [Display(Name = "predmetDbFK")]
        [BindProperty(SupportsGet = true)]
        public string predmetDbFK { get; set; }

        private readonly UserManager<User> userManager;
        private readonly RIIDBContext db;

        public FlashCardsModel(UserManager<User> userManager, RIIDBContext db)
        {
            this.db = db;
            this.userManager = userManager;
        }
        public void OnGet(string predmet)
        {
            Predmet = predmet;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            var user = await userManager.GetUserAsync(User);
            FlashCardData flashCardData = new FlashCardData
            {
                Opis = brojPoenaDbFK,
                Ocena = 0,
                Tezina = 0,
                NazivPredmeta = predmetDbFK,
                DatumZavrsetkaFK = datumZavrsetkaDbFK,
                User = user
            };
            await db.FlashCardData.AddAsync(flashCardData);
            await db.SaveChangesAsync();

            return RedirectToPage("/UserPages/Kvizovi");
        }
    }
}

Aplikacija/RIIEdition/Pages/UserPages/Kvizovi.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RIIEdition.Pages.UserPages
{
    public class KvizoviModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Aplikacija/RIIEdition/Pages/UserPages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RIIEdition.Data;

namespace RIIEdition.Pages.UserPages
{
    public class LoginModel : PageModel
    {
        private readonly UserManager<User> userManager;
        private readonly SignInManager<User> signInManager;
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        [BindProperty]
        [Display(Name = "Korisnicko ime")]
        public string UserName { get; set; }
        [BindProperty]
        [Required(ErrorMessage = "Ovo polje je obavezno")]
        [Display(Name = "Lozinka")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [BindProperty]

        [Display(Name = "Zapamti me")]
        public bool RememberMe { get; set; }
        [BindProperty(SupportsGet = true)]
        public IList<AuthenticationScheme> ExternalLogins { get; set; }

        public LoginModel(UserManager<User> userManager, SignInManager<User> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }
        public async Task OnGetAsync()
        {
            ExternalLogins = (await signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
        }
        public async Task<IActionResult> OnPostAsync()
        {
            ExternalLogins = (await signInManager.GetExternalAuthenticationSchemesAsync()).ToList();
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var user = await userManager.FindByNameAsync(UserName);

            //On ne udje ovde
            if (user != null && await userManager.CheckPasswordAsync(user, Password))
            {

                var result = await signInManager.PasswordSignInAsync(UserName, Password, RememberMe, false);
                if (result.Succeeded)
                {

                    return RedirectToPage("/Index");
                }
                else
                {

                    ModelState.AddModelError("", "Logovanje nije uspelo, molimo pokusajte ponovo");

                }
            }
            else
            {
                ModelState.AddModelError("", "Pogresili ste sifru ili korisnicko ime");
            }
            return Page();
        }
        public IActionResult OnPostGoogle(string provider)
        {

            var redirectUrl = "https://localhost:5001/UserPages/ExternalLoginCallback";
            var properties = signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);
            return new ChallengeResult(provider, properties);
        }
    }
}

Aplikacija/RIIEdition/Pages/UserPages/Materijali.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RIIEdition.Pages.UserPages
{
    public class MaterijaliModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Aplikacija/RIIEdition/Pages/UserPages/BazaBlanketa.cshtml
@page
@model RIIEdition.Pages.UserPages.BazaBlanketaModel
@{
}
@section css
{
<link rel="stylesheet" href="~/css/bazablanketa.css" />

}
@section Scripts
{
<script src="~/js/bazablanketa.js"></script>
}

<body>
  <partial name="_HeaderPartial" />
  <div class="container">
    <main role="main">
      <h1 class="m-4">Baza podataka blanketa</h1>
      @if(Model.MaterijalData.Count!=0)
      {

      @foreach(var blanket in Model.MaterijalData)
      {
      <div class="row justify-content-between">
        <div class="box ">
          <div class="about">
            <h2>Naziv:@blanket.NazivMaterijala</h2>
            <p>Predmet:@blanket.PredmetMaterijala
            </p>

          </div>
          <div class="figure">

          </div>

        </div>
        <div class="user-raiting col">
          <!--User raitong blanketi-->
          <span class="heading">User Rejting</span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star "></span>
          <span class="fa fa-star"></span>
          <p class="opis">4.1 zasnovano na 254 ocene.</p>
          <hr style="border:3px solid #f1f1f1">

          <div class="side">
            <div> 5</div>
          </div>
          <div class="middle">
            <div class="bar-container">
              <div class="bar-5"></div>
            </div>
          </div>
          <div class="side right">
            <div class="broj5">@blanket.brojOcenaPet</div>
          </div>
          <div class="side">
            <div> 4</div>
          </div>
          <div class="middle">
            <div class="bar-container">
              <div class="bar-4"></div>
            </div>
          </div>
          <div class="side right">
            <div class="broj4">@blanket.brojOcenaCetiri</div>
          </div>
          <div class="side">
            <div> 3</div>
          </div>
          <div class="middle">
            <div class="bar-container">
              <div class="bar-3"></div>
            </div>
          </div>
          <div class="side right">
            <div class="broj3">@blanket.brojOcenaTri</div>
          </div>
          <div class="side">
            <div> 2</div>
          </div>
          <div class="middle">
            <div class="bar-container">
              <div class="bar-2"></div>
            </div>
          </div>
          <div class="side right">
            <div class="broj2">@blanket.brojOcenaDva</div>
          </div>
          <div class="side">
            <div> 1</div>
          </div>
          <div class="middle">
            <div class="bar-container">
              <div class="bar-1"></div>
            </div>
          </div>
          <div class="side right">
            <div class="broj1">@blanket.brojOcenaJedan</div>
          </div>
        </div>

      </div>

      @if(signInManager.IsSignedIn(User)){
      <a class="btn btn-secondary mb-4" asp-page="/UserPages/OceniBlanket" asp-route-id="@blanket.Id">
        Oceni <span class="fa fa-comment"></span></a>
      <a class="btn btn-secondary mb-4 text-white" onclick="javascript:saveFavorite('@Model.MyUser.Id', '@blanket.Id')"
        data-toggle="modal" data-target="#save-changes-modal">
        Favorizuj <span class="fa fa-comment"></span></a>
      }
      else{
      <a asp-page="/UserPages/Login" class="pink-link">Ulogujete se da komentarisete i ocenite</a>
      }
      }

      }
      else {
      <h2 class="m-3">Nemata unetih blanketa u bazi</h2>
      }
    </main>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="save-changes-modal" tabindex="-1" role="dialog" aria-labelledby="save-changes-modalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="save-changes-modalLabel">Favorizuj</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body" id="save-changes-modal-body">
          Želite li favorizujete ovaj blanket? <br>
          Potvrdom se promena čuva za naredni pristup profilu.
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" onclick="javascript:undoLatestChange()"
            data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" data-dismiss="modal">Save changes</button>
        </div>
      </div>
    </div>
  </div>
  <partial name="_ScriptsPartial" />
</body>

Aplikacija/RIIEdition/Pages/UserPages/BlanketNapravi.cshtml
@page
@model RIIEdition.Pages.UserPages.BlanketNapraviModel
@{
}
@section css
{
<link rel="stylesheet" href="~/css/blanketnapravi.css" />
}
@section Scripts
{
<script src="~/js/napraviblanket.js"></script>
}

<body>
    <partial name="_HeaderPartial" />

    <div class="container">
        <form method="post">
            <div class="white-mode col-lg-8 col col-md-10 col-sm-12 blanket">

                <input asp-for="PitanjaMaterijala" id="skuppitanja" />
                <input asp-for="OdgovoriMaterijala" id="skupodgovora" />

                <div class="form-group">
                    <label asp-for="NazivMaterijala"></label>
                    <input asp-for="NazivMaterijala" id="nmaterijala" class="form-control " />
                    <span class="text-danger mt-2 mb-2" id="nazivMaterijala"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PredmetMaterijala"></label>
                    <input asp-for="PredmetMaterijala" id="pmaterijala" class="form-control " />
                    <span class="text-danger mt-2 mb-2" id="predmetMaterijala"></span>
                </div>
                <div class="form-group" id="izaberiBrojPitanja">
                    <label>Unesiti broj pitanja koji zelite da dodate:</label>
                    <input class="form-control brojPitanja" type="number" />
                    <span class="text-danger mt-2 mb-2" id="greskaBrojPitanja"></span>
                </div>
                <div class="ZaPitanja">

                </div>
                <div class="dugmici">
                    <a class="btn btn-danger" onclick="obrisiPitanje()">Obrisi jedno pitanje</a>
                    <a class="btn btn-primary" onclick="dodajPitanje()">Dodaj jedno pitanje</a>
                </div>
                <div class="sumbitFormu">
                    <a class="btn btn-info mt-2" onclick="prikaziKocku()">Napravi mi blanket</a>

                </div>

                <div class="mojButton">
                    <a href="#" onclick="generisiPitanja()">
                        <span>DALJE</span>
                        <span></span>
                        <span></span>
                        <span>DALJE</span>

                    </a>
                </div>

                <!-- 3D Checkbox-->
                <div class="mojcheck">
                    <div class=" mili">Tamna pozadina</div>
                    <div class="center">
                        <input type="checkbox" name="" class="dark" onchange="promeni()" />
                        <span>On</span>
                        <span>Off</span>
                    </div>
                </div>
                <!-- 3D kocka-->
            </div>

            <h3 id="obavestenje" class="bg-primary rounded mt-5 p-3">Vas blanket je zapamcen.Kliknite na kocku da
                nastavite</h3>
            <div class="mojaKocka">
                <div class="cube">
                    <span></span>
                    <span></span>
                    <span></span>
                    <button type="submit" class="submitForma"></button>

                </div>

            </div>

        </form>

    </div>

    <partial name="_ScriptsPartial" />

</body>

Aplikacija/RIIEdition/Pages/UserPages/ConfirmEmail.cshtml
@page
@model RIIEdition.Pages.UserPages.ConfirmEmailModel
@{
}

<head>
    <link rel="stylesheet" href="~/css/confirm-email.css" />
    <style>
        .jumbotron {
            opacity: 1;
        }

        .jumbotron1 {
            opacity: 0.5;
        }

        .jumbotron2 {
            opacity: 0.5;
        }
    </style>
</head>

<body>
    <partial name="_HeaderPartial" />
    <div class="container">
        <main role="main">
            <div class="container h-100">
                <div class="row align-items-left h-100">
                    <div class="col-6 ml-auto">
                        <div class="jumbotron jumbotron1">

                        </div>
                    </div>
                </div>
            </div>
            <div class="container h-100">
                <div class="row align-items-center h-100">
                    <div class="col-6 ml-auto">
                        <div class="jumbotron text-center">
                            <img src="~/AppPictures/email.png" class="rounded mx-auto d-block mb-1" alt="...">
                            <h3 class="mt-2">Potvrda email adrese</h3>
                            Poslat je email zarad potvrde validnosti Vase email adrese. Nakon dobijanja email-a pratite
                            link kako bi ste dovršili registraciju.
                        </div>
                    </div>
                </div>
            </div>
            <div class="container h-100">
                <div class="row align-items-center h-100">
                    <div class="col-6 ml-auto">
                        <div class="jumbotron jumbotron2">

                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
    <partial name="_ScriptsPartial" />

</body>

Aplikacija/RIIEdition/Pages/UserPages/EditUserProfile.cshtml
@page
@model RIIEdition.Pages.UserPages.EditUserProfileModel
@{
}

<body>
  <partial name="_HeaderPartial" />
  <div class="container">
    <main role="main">

    </main>
  </div>
  <partial name="_ScriptsPartial" />

</body>

Aplikacija/RIIEdition/Pages/UserPages/Login.cshtml
@page
@model RIIEdition.Pages.UserPages.LoginModel
@{
    int k=0;
}
@section css
{
    <link rel="stylesheet" href="~/css/Index.css" />
    

}
@section Scripts
{
    
}

<body class="books">
  <partial name="_HeaderPartial" />
    
        <main role="main" >
            <div class="centriraj">
           <div class="container w-100">
   
    <h3 class="text-center text-white">Molim vas ulogujte se</h3>
        <div asp-validation-summary="All" class="text-danger">

   </div>
<form method="post">

    <div class="form-group">
        <label asp-for="UserName" class="text-white"></label>
        <input asp-for="UserName" class="form-control "/>
        <span asp-validation-for="UserName" class="text-danger "></span>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="text-white"></label>
        <input asp-for="Password" class="form-control "/>
        <span asp-validation-for="Password" class="text-danger "></span>
    </div>
    <div class="form-group">
        <div>
        <label asp-for="RememberMe" class="text-white"></label>
        <input asp-for="RememberMe"  class="custom-checkbox"/>
        </div>
        
        </div>
        <div class="row justify-content-end mr-3">
            <button type="submit" class="btn btn-primary">Uloguj se</button>
        </div>
        <div class="row justify-content-center">
           <div class="text-white"> Nemas nalog?&nbsp;<a asp-page="/UserPages/Register" class="text-primary">Registruj se!</a></div>

        </div>
        <div class="row justify-content-center"> <a class="text-primary" asp-page="/UserPages/ResetPassword">Zaboravili ste sifru
        </a></div>
    </form>
   <hr class="hrar" />
    <form method="post">
        
    @foreach (var provider in Model.ExternalLogins)
    {
        @if(k==0)
        {
         k++;
        
        <div class="row justify-content-center w-100">
        <button class="btn btn-danger w-50 mt-3 mb-3" type="submit" name="provider" value="@provider.Name"
        title="Login using @provider.DisplayName" asp-page-handler="Google">
        <span class="fa fa-google"></span>
        </button>
        </div>
        }
        else
        {
            <div class="row justify-content-center w-100">
        <button class="btn btn-primary w-50 mb-3" type="submit" name="provider" value="@provider.Name"
        title="Login using @provider.DisplayName" asp-page-handler="Google">
        <span class="fa fa-facebook"></span>
        </button>
        </div>

        }
    }

     </form>
</div>
</div>

        </main>
    
<partial name="_ScriptsPartial" />

</body>

Aplikacija/RIIEdition/Pages/UserPages/Logout.cshtml
@page
@model RIIEdition.Pages.UserPages.LogoutModel
@{
}
<body>
  <partial name="_HeaderPartial" />
    <div class="container">
        <main role="main" >
          
        </main>
    </div>
<partial name="_ScriptsPartial" />

</body>